steps:

  - name: gcr.io/cloud-builders/gsutil
    args: [ 'cp', 'gs://$_BETTERMS_BUCKET/plugin-dependencies/*', './deps' ]

  - name: maven:3.9.6-amazoncorretto-17-al2023
    entrypoint: mvn
    args: [
      'install:install-file',
      '-Dfile=deps/craftbukkit-1.17.1.jar',
      '-DgroupId=org.bukkit',
      '-DartifactId=craftbukkit',
      '-Dversion=1.17.1-R0.1-SNAPSHOT',
      '-Dpackaging=jar'
    ]

  - name: maven:3.9.6-amazoncorretto-17-al2023
    entrypoint: mvn
    args: [
      'install:install-file',
      '-Dfile=deps/spigot-1.17.1.jar',
      '-DgroupId=org.spigotmc',
      '-DartifactId=spigot-api',
      '-Dversion=1.17.1-R0.1-SNAPSHOT',
      '-Dpackaging=jar'
    ]

  - name: maven:3.9.6-amazoncorretto-17-al2023
    entrypoint: mvn
    args: [ 'clean', 'package' ]

  - name: gcr.io/cloud-builders/gsutil
    args: [ 'cp', 'target/betterms-jar-with-dependencies.jar', 'gs://$_BETTERMS_BUCKET/built-plugins' ]

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - '-c'
      - gcloud builds triggers run betterms-mc-server-trigger
